# -*- coding: utf-8 -*-
"""dl5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Iv38B853O6JYXDH3X50COF7UdaCfpeo
"""

!pip install tensorflow matplotlib scikit-learn

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

np.random.seed(42)

num_samples = 5000
num_tx = 2
num_rx = 2

X = np.random.choice([-1,1], size=(num_samples, num_tx))

H = np.random.randn(num_samples, num_rx, num_tx)

noise = 0.1 * np.random.randn(num_samples, num_rx)

Y = np.zeros((num_samples, num_rx))

for i in range(num_samples):
    Y[i] = H[i].dot(X[i]) + noise[i]

features = Y
labels = (X[:,0] + 1) / 2

X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=16,
    validation_split=0.2
)
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Training","Validation"])

plt.show()